name: Selene
on:
  push:
    paths: '**.lua'
    branches: 'main'
  pull_request:
    paths: '**.lua'
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Install Selene'
        run: |
          wget -O selene.zip https://github.com/Kampfkarren/selene/releases/download/0.11.0/selene-0.11.0-linux.zip
          unzip selene.zip
          chmod +x ./selene

      - name: 'Generate Roblox Std'
        run: |
          ./selene generate-roblox-std

      - name: 'Run Selene'
        run: |
          ./selene src/roblox.lua src/vanilla.lua
